### ISSUE TITLE
Composer package name is invalid as an OctoberCMS plugin

### ISSUE THREAD

**Issue by LukeTowers** [weglot/oc-translate-plugin#6]
See http://octobercms.com/help/guidelines/developer#repository-naming. Repository name should ideally be `oc-translate-plugin` but at the very least the package name needs to be `oc-translate-plugin` in order for the composer installers package to work correctly

**Comment by LukeTowers** [comment]
Looks good to me @Korbeil! Don't forget to update your settings on the marketplace build process if you've setup auto builds

**Comment by Korbeil** [comment]
Yes, I've done that with that `1.4.2` release !
